/**
 * Google Apps Script for TrendAI V2 Results Tracking
 * 
 * SETUP:
 * 1. Create Google Sheet named "TrendAI Results"
 * 2. Add headers: Timestamp | Keyword | Score | Trend | Rakuten | YouTube | Yahoo | Website | Generated By
 * 3. Tools → Script Editor → Paste this code
 * 4. Deploy → New deployment → Web app
 * 5. Execute as: Me
 * 6. Who has access: Anyone
 * 7. Copy deployment URL and add to frontend
 */

function doPost(e) {
  try {
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    const data = JSON.parse(e.postData.contents);
    
    // Append row with timestamp
    sheet.appendRow([
      new Date(),
      data.keyword || '',
      data.score || 0,
      data.trend || 0,
      data.rakuten || '',
      data.youtube || 0,
      data.yahoo || 0,
      data.websiteGenerated ? 'Yes' : 'No',
      data.generatedBy || 'unknown'
    ]);
    
    return ContentService
      .createTextOutput(JSON.stringify({ status: 'success' }))
      .setMimeType(ContentService.MimeType.JSON);
      
  } catch (error) {
    return ContentService
      .createTextOutput(JSON.stringify({ status: 'error', message: error.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

function doGet(e) {
  // Health check endpoint
  return ContentService
    .createTextOutput(JSON.stringify({ status: 'ok', timestamp: new Date() }))
    .setMimeType(ContentService.MimeType.JSON);
}

/**
 * FRONTEND INTEGRATION:
 * 
 * Add this to index.html after successful analysis:
 * 
 * const SHEETS_URL = 'YOUR_DEPLOYMENT_URL_HERE';
 * 
 * async function sendToSheets(data) {
 *   try {
 *     await fetch(SHEETS_URL, {
 *       method: 'POST',
 *       headers: { 'Content-Type': 'application/json' },
 *       body: JSON.stringify({
 *         keyword: data.trend.keyword,
 *         score: data.validation.score,
 *         trend: data.trend.score,
 *         rakuten: data.rakuten.demandSignal.level,
 *         youtube: data.youtube.totalResults,
 *         yahoo: data.yahoo.totalHits,
 *         websiteGenerated: !!data.result.websiteHTML,
 *         generatedBy: data.result.generatedBy
 *       })
 *     });
 *   } catch (err) {
 *     console.error('Sheets error:', err);
 *   }
 * }
 * 
 * // Call after rendering results:
 * sendToSheets(currentData);
 */
